/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller and the role bindings that apply to them */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/role-bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRoleBindings"];
        put?: never;
        post: operations["createRoleBinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/role-bindings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteRoleBinding"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCustomers"];
        put?: never;
        post: operations["createCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
            };
            cookie?: never;
        };
        get: operations["getCustomer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateCustomer"];
        trace?: never;
    };
    "/api/v1/customers/{customer}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
            };
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateProject"];
        trace?: never;
    };
    "/api/v1/projects/{project}/items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        get: operations["listItems"];
        put?: never;
        post: operations["createItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/runnable": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        /** Ready tickets whose blockers are all resolved */
        get: operations["listRunnable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        get: operations["getItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateItem"];
        trace?: never;
    };
    "/api/v1/items/{item}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transitionItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item}/history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        get: operations["getItemHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item}/dependencies": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        get: operations["listDependencies"];
        put?: never;
        post: operations["addDependency"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dependencies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeDependency"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @enum {string} */
            error: "invalid_argument" | "unauthenticated" | "forbidden" | "not_found" | "already_exists" | "conflict" | "internal";
            message: string;
        };
        Me: {
            subject: string;
            email: string;
            name: string;
            groups: string[];
            bindings: components["schemas"]["RoleBinding"][];
        };
        Role: {
            role: string;
            actions: string[];
        };
        RoleList: {
            items: components["schemas"]["Role"][];
        };
        RoleBinding: {
            id: string;
            claim: string;
            value: string;
            /** @enum {string} */
            role: "org-admin" | "customer-admin" | "engineer" | "approver" | "viewer";
            /** @description organization, customer:<key> or project:<key> */
            scope: string;
            bootstrap: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        RoleBindingList: {
            items: components["schemas"]["RoleBinding"][];
        };
        CreateRoleBinding: {
            claim: string;
            value: string;
            role: string;
            scope: string;
        };
        Customer: {
            id: string;
            key: string;
            name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            version: number;
        };
        CustomerList: {
            items: components["schemas"]["Customer"][];
        };
        CreateCustomer: {
            key: string;
            name: string;
        };
        UpdateCustomer: {
            name: string;
            /** Format: int64 */
            version: number;
        };
        Project: {
            id: string;
            key: string;
            /** @description Customer key */
            customer: string;
            name: string;
            description: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            version: number;
        };
        ProjectList: {
            items: components["schemas"]["Project"][];
        };
        CreateProject: {
            key: string;
            name: string;
            description?: string;
        };
        UpdateProject: {
            name: string;
            description?: string;
            /** Format: int64 */
            version: number;
        };
        /** @enum {string} */
        ItemKind: "milestone" | "epic" | "ticket";
        /** @enum {string} */
        ItemState: "open" | "backlog" | "ready" | "in_progress" | "waiting_for_answer" | "paused" | "done" | "cancelled";
        /** @enum {string} */
        TicketType: "feature" | "bug" | "tech_debt" | "docs" | "spike";
        Policy: {
            /** @enum {string} */
            review_mode: "agent" | "agent+human";
            /** @enum {string} */
            merge_mode: "auto" | "manual";
        };
        Item: {
            id: string;
            key: string;
            /** @description Project key */
            project: string;
            kind: components["schemas"]["ItemKind"];
            title: string;
            description: string;
            state: components["schemas"]["ItemState"];
            /** @description Current pipeline stage while in progress */
            stage?: string;
            type?: components["schemas"]["TicketType"];
            acceptance_criteria?: string[];
            policy?: components["schemas"]["Policy"];
            /** @description Epic key */
            epic?: string;
            /** @description Milestone key */
            milestone?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            version: number;
        };
        ItemList: {
            items: components["schemas"]["Item"][];
        };
        CreateItem: {
            kind: components["schemas"]["ItemKind"];
            title: string;
            description?: string;
            type?: components["schemas"]["TicketType"];
            acceptance_criteria?: string[];
            policy?: components["schemas"]["Policy"];
            epic?: string;
            milestone?: string;
        };
        UpdateItem: {
            /** Format: int64 */
            version: number;
            title?: string;
            description?: string;
            type?: components["schemas"]["TicketType"];
            acceptance_criteria?: string[];
            policy?: components["schemas"]["Policy"];
            /** @description Epic key; empty string removes */
            epic?: string;
            /** @description Milestone key; empty string removes */
            milestone?: string;
        };
        Transition: {
            state: components["schemas"]["ItemState"];
            /** Format: int64 */
            version: number;
        };
        Actor: {
            /** @enum {string} */
            kind: "human" | "service" | "system";
            subject: string;
            acting_for?: string;
        };
        Event: {
            /** Format: int64 */
            seq: number;
            type: string;
            /** Format: date-time */
            occurred_at: string;
            actor: components["schemas"]["Actor"];
            payload?: {
                [key: string]: unknown;
            };
        };
        EventList: {
            items: components["schemas"]["Event"][];
        };
        ItemRef: {
            key: string;
            kind: components["schemas"]["ItemKind"];
            title: string;
            state: components["schemas"]["ItemState"];
        };
        /** @enum {string} */
        DependencyType: "blocks" | "blocked_by" | "relates";
        Dependency: {
            id: string;
            type: components["schemas"]["DependencyType"];
            item: components["schemas"]["ItemRef"];
        };
        DependencyList: {
            items: components["schemas"]["Dependency"][];
        };
        AddDependency: {
            type: components["schemas"]["DependencyType"];
            /** @description Key of the other item */
            item: string;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Customer key */
        Customer: string;
        /** @description Project key */
        Project: string;
        /** @description Item key, e.g. WEB-42 */
        Item: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRoleBindings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleBindingList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createRoleBinding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleBinding"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleBinding"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteRoleBinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listCustomers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomer"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomer"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProject"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProject"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listItems: {
        parameters: {
            query?: {
                kind?: components["schemas"]["ItemKind"];
                state?: components["schemas"]["ItemState"];
                /** @description Epic key */
                epic?: string;
                /** @description Milestone key */
                milestone?: string;
            };
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItem"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRunnable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItem"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    transitionItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transition"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getItemHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listDependencies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DependencyList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    addDependency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddDependency"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dependency"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    removeDependency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
}
