/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller and the role bindings that apply to them */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/role-bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRoleBindings"];
        put?: never;
        post: operations["createRoleBinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/role-bindings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteRoleBinding"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCustomers"];
        put?: never;
        post: operations["createCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
            };
            cookie?: never;
        };
        get: operations["getCustomer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateCustomer"];
        trace?: never;
    };
    "/api/v1/customers/{customer}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
            };
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateProject"];
        trace?: never;
    };
    "/api/v1/projects/{project}/items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        get: operations["listItems"];
        put?: never;
        post: operations["createItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/runnable": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        /** Ready tickets whose blockers are all resolved */
        get: operations["listRunnable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/changesets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        /** The project's plan changesets, newest first */
        get: operations["listChangesets"];
        put?: never;
        /** Propose planning changes for a human to approve */
        post: operations["proposeChangeset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/changesets/{changeset}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Changeset ID */
                changeset: components["parameters"]["Changeset"];
            };
            cookie?: never;
        };
        get: operations["getChangeset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/changesets/{changeset}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Changeset ID */
                changeset: components["parameters"]["Changeset"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply the approved operations atomically (humans only) */
        post: operations["applyChangeset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/changesets/{changeset}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Changeset ID */
                changeset: components["parameters"]["Changeset"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject the whole changeset (humans only) */
        post: operations["rejectChangeset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/planner/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        /** The project's planner sessions, most recently active first */
        get: operations["listPlannerSessions"];
        put?: never;
        /** Start a planner chat (send messages over the realtime API) */
        post: operations["createPlannerSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planner/sessions/{session}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Planner session ID */
                session: components["parameters"]["PlannerSession"];
            };
            cookie?: never;
        };
        /** A planner session with its full transcript */
        get: operations["getPlannerSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        /** The ticket's runs, oldest first */
        get: operations["listRuns"];
        put?: never;
        /** Queue a run of the ticket by hand (run.manage) */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/execution": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        /** How the project's runs execute (version 0 when never set) */
        get: operations["getExecutionSettings"];
        /** Replace the project's execution settings (project.update) */
        put: operations["setExecutionSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run ID */
                run: components["parameters"]["Run"];
            };
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run ID */
                run: components["parameters"]["Run"];
            };
            cookie?: never;
        };
        /** The run's output after a sequence number */
        get: operations["getRunLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run ID */
                run: components["parameters"]["Run"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a queued or active run (run.manage) */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        get: operations["getItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateItem"];
        trace?: never;
    };
    "/api/v1/items/{item}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transitionItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item}/history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        get: operations["getItemHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item}/dependencies": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        get: operations["listDependencies"];
        put?: never;
        post: operations["addDependency"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dependencies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeDependency"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
            };
            cookie?: never;
        };
        /** Customer defaults and project overrides, without secrets */
        get: operations["listCredentials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer}/credentials/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
                provider: components["parameters"]["Provider"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["setCustomerCredential"];
        post?: never;
        delete: operations["deleteCustomerCredential"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/credentials/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
                provider: components["parameters"]["Provider"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["setProjectCredential"];
        post?: never;
        delete: operations["deleteProjectCredential"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        /** LLM token usage of the project, grouped by ticket or model */
        get: operations["getProjectUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer}/knowledge/entries": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
            };
            cookie?: never;
        };
        /** Entries of the customer's knowledge space (served by Knowledge through Core) */
        get: operations["listKnowledgeEntries"];
        put?: never;
        post: operations["createKnowledgeEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer}/knowledge/search": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
            };
            cookie?: never;
        };
        /** Hybrid full-text and semantic search in the customer's knowledge space */
        get: operations["searchKnowledge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer}/knowledge/entries/{entry}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
                /** @description Knowledge entry ID */
                entry: components["parameters"]["Entry"];
            };
            cookie?: never;
        };
        get: operations["getKnowledgeEntry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateKnowledgeEntry"];
        trace?: never;
    };
    "/api/v1/customers/{customer}/knowledge/entries/{entry}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
                /** @description Knowledge entry ID */
                entry: components["parameters"]["Entry"];
            };
            cookie?: never;
        };
        get: operations["listKnowledgeVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Skills defined at exactly one scope */
        get: operations["listSkills"];
        put?: never;
        post: operations["createSkill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/{skill}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Skill ID */
                skill: components["parameters"]["Skill"];
            };
            cookie?: never;
        };
        get: operations["getSkill"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSkillDraft"];
        trace?: never;
    };
    "/api/v1/skills/{skill}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Skill ID */
                skill: components["parameters"]["Skill"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snapshot the draft as the next immutable version */
        post: operations["publishSkill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/{skill}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Skill ID */
                skill: components["parameters"]["Skill"];
            };
            cookie?: never;
        };
        get: operations["listSkillVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/{skill}/versions/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Skill ID */
                skill: components["parameters"]["Skill"];
                number: string;
            };
            cookie?: never;
        };
        get: operations["getSkillVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/skills": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        /** The project's effective skills (organization → customer → project, pins applied) */
        get: operations["resolveProjectSkills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/skill-pins": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        /** The project's pins, including disabled skills (which resolution leaves out) */
        get: operations["listProjectSkillPins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/skills/{name}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
                name: string;
            };
            cookie?: never;
        };
        get?: never;
        put: operations["pinProjectSkill"];
        post?: never;
        delete: operations["unpinProjectSkill"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hybrid search over tickets, epics, milestones and skills the caller may read */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @enum {string} */
            error: "invalid_argument" | "unauthenticated" | "forbidden" | "not_found" | "already_exists" | "conflict" | "internal";
            message: string;
        };
        Me: {
            subject: string;
            email: string;
            name: string;
            groups: string[];
            bindings: components["schemas"]["RoleBinding"][];
        };
        Role: {
            role: string;
            actions: string[];
        };
        RoleList: {
            items: components["schemas"]["Role"][];
        };
        RoleBinding: {
            id: string;
            claim: string;
            value: string;
            /** @enum {string} */
            role: "org-admin" | "customer-admin" | "engineer" | "approver" | "viewer";
            /** @description organization, customer:<key> or project:<key> */
            scope: string;
            bootstrap: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        RoleBindingList: {
            items: components["schemas"]["RoleBinding"][];
        };
        CreateRoleBinding: {
            claim: string;
            value: string;
            role: string;
            scope: string;
        };
        Customer: {
            id: string;
            key: string;
            name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            version: number;
        };
        CustomerList: {
            items: components["schemas"]["Customer"][];
        };
        CreateCustomer: {
            key: string;
            name: string;
        };
        UpdateCustomer: {
            name: string;
            /** Format: int64 */
            version: number;
        };
        Project: {
            id: string;
            key: string;
            /** @description Customer key */
            customer: string;
            name: string;
            description: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            version: number;
        };
        ProjectList: {
            items: components["schemas"]["Project"][];
        };
        CreateProject: {
            key: string;
            name: string;
            description?: string;
        };
        UpdateProject: {
            name: string;
            description?: string;
            /** Format: int64 */
            version: number;
        };
        /** @enum {string} */
        ItemKind: "milestone" | "epic" | "ticket";
        /** @enum {string} */
        ItemState: "open" | "backlog" | "ready" | "in_progress" | "waiting_for_answer" | "paused" | "done" | "cancelled";
        /** @enum {string} */
        TicketType: "feature" | "bug" | "tech_debt" | "docs" | "spike";
        Policy: {
            /** @enum {string} */
            review_mode: "agent" | "agent+human";
            /** @enum {string} */
            merge_mode: "auto" | "manual";
        };
        Item: {
            id: string;
            key: string;
            /** @description Project key */
            project: string;
            kind: components["schemas"]["ItemKind"];
            title: string;
            description: string;
            state: components["schemas"]["ItemState"];
            /** @description Current pipeline stage while in progress */
            stage?: string;
            type?: components["schemas"]["TicketType"];
            acceptance_criteria?: string[];
            policy?: components["schemas"]["Policy"];
            /** @description Epic key */
            epic?: string;
            /** @description Milestone key */
            milestone?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            version: number;
        };
        ItemList: {
            items: components["schemas"]["Item"][];
        };
        CreateItem: {
            kind: components["schemas"]["ItemKind"];
            title: string;
            description?: string;
            type?: components["schemas"]["TicketType"];
            acceptance_criteria?: string[];
            policy?: components["schemas"]["Policy"];
            epic?: string;
            milestone?: string;
        };
        UpdateItem: {
            /** Format: int64 */
            version: number;
            title?: string;
            description?: string;
            type?: components["schemas"]["TicketType"];
            acceptance_criteria?: string[];
            policy?: components["schemas"]["Policy"];
            /** @description Epic key; empty string removes */
            epic?: string;
            /** @description Milestone key; empty string removes */
            milestone?: string;
        };
        Transition: {
            state: components["schemas"]["ItemState"];
            /** Format: int64 */
            version: number;
        };
        Actor: {
            /** @enum {string} */
            kind: "human" | "service" | "system";
            subject: string;
            acting_for?: string;
        };
        Event: {
            /** Format: int64 */
            seq: number;
            type: string;
            /** Format: date-time */
            occurred_at: string;
            actor: components["schemas"]["Actor"];
            payload?: {
                [key: string]: unknown;
            };
        };
        EventList: {
            items: components["schemas"]["Event"][];
        };
        ItemRef: {
            key: string;
            kind: components["schemas"]["ItemKind"];
            title: string;
            state: components["schemas"]["ItemState"];
        };
        /** @enum {string} */
        DependencyType: "blocks" | "blocked_by" | "relates";
        Dependency: {
            id: string;
            type: components["schemas"]["DependencyType"];
            item: components["schemas"]["ItemRef"];
        };
        DependencyList: {
            items: components["schemas"]["Dependency"][];
        };
        AddDependency: {
            type: components["schemas"]["DependencyType"];
            /** @description Key of the other item */
            item: string;
        };
        ExecutionSettings: {
            project: string;
            /** @description https, ssh, git@host:path or file URL; empty: no repository */
            repo_url: string;
            default_branch: string;
            /** @description Devcontainer image of the runs */
            image: string;
            /** @description Shell commands run in the repository before each session */
            setup: string[];
            env: {
                [key: string]: string;
            };
            /** @description {ticket}, {slug}, {type} */
            branch_template: string;
            git_name: string;
            git_email: string;
            /** Format: date-time */
            updated_at?: string;
            /** Format: int64 */
            version: number;
        };
        SetExecutionSettings: {
            repo_url?: string;
            default_branch?: string;
            image?: string;
            setup?: string[];
            env?: {
                [key: string]: string;
            };
            branch_template?: string;
            git_name?: string;
            git_email?: string;
            /**
             * Format: int64
             * @description The version read (0 the first time)
             */
            version: number;
        };
        /** @enum {string} */
        RunStatus: "queued" | "starting" | "running" | "succeeded" | "failed" | "cancelled";
        RunSpec: {
            /** @description Container image (container backends) */
            image?: string;
            command: string[];
            env?: {
                [key: string]: string;
            };
            workdir?: string;
            /** @description 0: the Runner's default */
            timeout_seconds?: number;
        };
        Run: {
            id: string;
            project: string;
            ticket: string;
            stage: string;
            status: components["schemas"]["RunStatus"];
            spec: components["schemas"]["RunSpec"];
            /** @description The ticket branch the run works on */
            branch?: string;
            runner?: string;
            exit_code?: number;
            error?: string;
            created_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string;
            /** Format: int64 */
            version: number;
        };
        RunList: {
            items: components["schemas"]["Run"][];
        };
        CreateRun: {
            /** @description Pipeline stage, e.g. implement */
            stage: string;
            spec: components["schemas"]["RunSpec"];
        };
        RunLog: {
            /** Format: int64 */
            seq: number;
            /** @enum {string} */
            stream: "stdout" | "stderr" | "system";
            text: string;
            /** Format: date-time */
            at: string;
        };
        RunLogList: {
            items: components["schemas"]["RunLog"][];
        };
        PlannerSession: {
            id: string;
            project: string;
            title: string;
            created_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** @description The planner is answering */
            running: boolean;
        };
        PlannerSessionList: {
            items: components["schemas"]["PlannerSession"][];
        };
        CreatePlannerSession: {
            title: string;
        };
        PlannerBlock: {
            /** @enum {string} */
            type: "text" | "tool_use" | "tool_result";
            /** @description text; tool_result output */
            text?: string;
            tool_use_id?: string;
            /** @description Tool name (tool_use) */
            name?: string;
            /** @description Tool input (tool_use) */
            input?: {
                [key: string]: unknown;
            };
            is_error?: boolean;
        };
        PlannerUsage: {
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            /** Format: int64 */
            cache_read_tokens: number;
            /** Format: int64 */
            cache_write_tokens: number;
        };
        PlannerMessage: {
            /** Format: int64 */
            seq: number;
            /**
             * @description Tool results are user messages
             * @enum {string}
             */
            role: "user" | "assistant";
            content: components["schemas"]["PlannerBlock"][];
            /** @description Human who wrote a user text message */
            author?: string;
            stop_reason?: string;
            usage: components["schemas"]["PlannerUsage"];
            /** Format: date-time */
            created_at: string;
        };
        PlannerTranscript: {
            id: string;
            project: string;
            title: string;
            created_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            running: boolean;
            messages: components["schemas"]["PlannerMessage"][];
        };
        /** @enum {string} */
        ChangesetStatus: "proposed" | "applied" | "rejected";
        /** @description Key of an existing item of the project ("WEB-12"), or "$" + the ref of an earlier create_item operation ("$login") */
        ItemReference: string;
        ChangesetCreateItem: {
            kind: components["schemas"]["ItemKind"];
            title: string;
            description?: string;
            type?: components["schemas"]["TicketType"];
            acceptance_criteria?: string[];
            policy?: components["schemas"]["Policy"];
            epic?: components["schemas"]["ItemReference"];
            milestone?: components["schemas"]["ItemReference"];
        };
        ChangesetUpdateItem: {
            /** @description Key of an existing item */
            item: string;
            title?: string;
            description?: string;
            type?: components["schemas"]["TicketType"];
            acceptance_criteria?: string[];
            policy?: components["schemas"]["Policy"];
            /** @description Item reference; "" removes the epic */
            epic?: string;
            /** @description Item reference; "" removes the milestone */
            milestone?: string;
        };
        ChangesetDependency: {
            from: components["schemas"]["ItemReference"];
            to: components["schemas"]["ItemReference"];
            /**
             * @description blocks: from blocks to
             * @enum {string}
             */
            type: "blocks" | "relates";
        };
        /** @description Exactly the payload matching kind is set. */
        ChangesetOperation: {
            /** @enum {string} */
            kind: "create_item" | "update_item" | "add_dependency";
            /** @description create_item: name later operations use as $ref */
            ref?: string;
            create?: components["schemas"]["ChangesetCreateItem"];
            update?: components["schemas"]["ChangesetUpdateItem"];
            dependency?: components["schemas"]["ChangesetDependency"];
        };
        ChangesetResult: {
            /** @description Created or updated item */
            key?: string;
            /** @description Added dependency ID */
            dependency?: string;
        };
        Changeset: {
            id: string;
            project: string;
            title: string;
            /** @description Markdown */
            summary: string;
            status: components["schemas"]["ChangesetStatus"];
            operations: components["schemas"]["ChangesetOperation"][];
            proposed_by: components["schemas"]["Actor"];
            /** Format: date-time */
            created_at: string;
            decided_by?: components["schemas"]["Actor"];
            /** Format: date-time */
            decided_at?: string;
            /** @description 0-based indices of applied operations */
            approved: number[];
            /** @description Per operation once applied; empty before */
            results: components["schemas"]["ChangesetResult"][];
            /** Format: int64 */
            version: number;
        };
        ChangesetList: {
            items: components["schemas"]["Changeset"][];
        };
        ProposeChangeset: {
            title: string;
            summary?: string;
            operations: components["schemas"]["ChangesetOperation"][];
        };
        ApplyChangeset: {
            /** @description 0-based indices of the approved operations */
            operations: number[];
        };
        Credential: {
            /** @enum {string} */
            provider: "anthropic" | "openai" | "git";
            /** @description Project key of an override; absent for the customer default */
            project?: string;
            base_url: string;
            /** @description Identifies the key without revealing it */
            fingerprint: string;
            /** Format: date-time */
            updated_at: string;
        };
        CredentialList: {
            items: components["schemas"]["Credential"][];
        };
        SetCredential: {
            /** @description Write-only; never returned */
            api_key: string;
            base_url?: string;
        };
        UsageTotals: {
            /** @description Ticket key or model of the group */
            key?: string;
            /** Format: int64 */
            requests: number;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            /** Format: int64 */
            cache_read_tokens: number;
            /** Format: int64 */
            cache_write_tokens: number;
        };
        UsageReport: {
            /** @enum {string} */
            group_by: "ticket" | "model";
            items: components["schemas"]["UsageTotals"][];
            total: components["schemas"]["UsageTotals"];
        };
        /** @enum {string} */
        KnowledgeKind: "document" | "decision" | "note" | "debt";
        KnowledgeEntry: {
            id: string;
            kind: components["schemas"]["KnowledgeKind"];
            title: string;
            /** @description Markdown */
            body: string;
            projects: string[];
            /** @description Linked tracker item keys */
            items: string[];
            /** Format: int64 */
            version: number;
            created_by: string;
            updated_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        KnowledgeEntryList: {
            items: components["schemas"]["KnowledgeEntry"][];
        };
        CreateKnowledgeEntry: {
            kind: components["schemas"]["KnowledgeKind"];
            title: string;
            body?: string;
            projects?: string[];
            items?: string[];
        };
        UpdateKnowledgeEntry: {
            /** Format: int64 */
            version: number;
            kind?: components["schemas"]["KnowledgeKind"];
            title?: string;
            body?: string;
            projects?: string[];
            items?: string[];
        };
        KnowledgeVersion: {
            /** Format: int64 */
            version: number;
            title: string;
            body: string;
            author: string;
            /** Format: date-time */
            created_at: string;
        };
        KnowledgeVersionList: {
            items: components["schemas"]["KnowledgeVersion"][];
        };
        KnowledgeSearchHit: {
            entry: components["schemas"]["KnowledgeEntry"];
            /** @description Fused rank score; higher is better */
            score: number;
        };
        KnowledgeSearchResult: {
            items: components["schemas"]["KnowledgeSearchHit"][];
        };
        /** @description Supporting text files by relative path */
        SkillFiles: {
            [key: string]: string;
        };
        Skill: {
            id: string;
            scope: string;
            name: string;
            /** @description Draft description */
            description: string;
            /** @description Draft SKILL.md body */
            body: string;
            files: components["schemas"]["SkillFiles"];
            /**
             * Format: int64
             * @description 0: never published
             */
            latest_version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: int64
             * @description Optimistic concurrency of the draft
             */
            version: number;
        };
        SkillList: {
            items: components["schemas"]["Skill"][];
        };
        CreateSkill: {
            scope: string;
            name: string;
            description: string;
            body?: string;
            files?: components["schemas"]["SkillFiles"];
        };
        UpdateSkillDraft: {
            /** Format: int64 */
            version: number;
            description?: string;
            body?: string;
            files?: components["schemas"]["SkillFiles"];
        };
        PublishSkill: {
            /** Format: int64 */
            version: number;
        };
        SkillVersion: {
            /** Format: int64 */
            number: number;
            description: string;
            body: string;
            files: components["schemas"]["SkillFiles"];
            published_by: string;
            /** Format: date-time */
            published_at: string;
        };
        SkillVersionList: {
            items: components["schemas"]["SkillVersion"][];
        };
        ResolvedSkill: {
            name: string;
            /** @description The most specific skill with this name */
            skill_id?: string;
            scope?: string;
            /**
             * Format: int64
             * @description Version the project uses; 0 when unusable (see problem)
             */
            version: number;
            /** Format: int64 */
            latest_version: number;
            pinned: boolean;
            /** @description Why the skill cannot be used as configured */
            problem?: string;
        };
        ResolvedSkillList: {
            items: components["schemas"]["ResolvedSkill"][];
        };
        SkillPin: {
            /**
             * Format: int64
             * @description 0: always the latest published version
             */
            version?: number;
            /** @description Exclude the skill from the project */
            disabled?: boolean;
        };
        ProjectSkillPin: {
            name: string;
            /**
             * Format: int64
             * @description 0: the latest published version
             */
            version: number;
            disabled: boolean;
        };
        ProjectSkillPinList: {
            items: components["schemas"]["ProjectSkillPin"][];
        };
        SearchHit: {
            /** @enum {string} */
            kind: "item" | "skill";
            /** @description Item key or skill name */
            ref: string;
            title: string;
            snippet: string;
            customer?: string;
            project?: string;
            /** @description Skills only */
            scope?: string;
            score: number;
        };
        SearchResult: {
            items: components["schemas"]["SearchHit"][];
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Customer key */
        Customer: string;
        /** @description Project key */
        Project: string;
        /** @description Skill ID */
        Skill: string;
        /** @description Run ID */
        Run: string;
        /** @description Planner session ID */
        PlannerSession: string;
        /** @description Changeset ID */
        Changeset: string;
        /** @description Knowledge entry ID */
        Entry: string;
        Provider: "anthropic" | "openai" | "git";
        /** @description Item key, e.g. WEB-42 */
        Item: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRoleBindings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleBindingList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createRoleBinding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleBinding"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleBinding"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteRoleBinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listCustomers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomer"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomer"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProject"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProject"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listItems: {
        parameters: {
            query?: {
                kind?: components["schemas"]["ItemKind"];
                state?: components["schemas"]["ItemState"];
                /** @description Epic key */
                epic?: string;
                /** @description Milestone key */
                milestone?: string;
            };
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItem"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRunnable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listChangesets: {
        parameters: {
            query?: {
                status?: components["schemas"]["ChangesetStatus"];
            };
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangesetList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    proposeChangeset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposeChangeset"];
            };
        };
        responses: {
            /** @description Proposed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Changeset"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getChangeset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Changeset ID */
                changeset: components["parameters"]["Changeset"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Changeset"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    applyChangeset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Changeset ID */
                changeset: components["parameters"]["Changeset"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyChangeset"];
            };
        };
        responses: {
            /** @description Applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Changeset"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    rejectChangeset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Changeset ID */
                changeset: components["parameters"]["Changeset"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Changeset"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listPlannerSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannerSessionList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createPlannerSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlannerSession"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannerSession"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getPlannerSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Planner session ID */
                session: components["parameters"]["PlannerSession"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannerTranscript"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRuns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRun"];
            };
        };
        responses: {
            /** @description Queued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getExecutionSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionSettings"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    setExecutionSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetExecutionSettings"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionSettings"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run ID */
                run: components["parameters"]["Run"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRunLogs: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Run ID */
                run: components["parameters"]["Run"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunLogList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run ID */
                run: components["parameters"]["Run"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItem"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    transitionItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transition"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getItemHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listDependencies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DependencyList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    addDependency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item key, e.g. WEB-42 */
                item: components["parameters"]["Item"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddDependency"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dependency"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    removeDependency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    setCustomerCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
                provider: components["parameters"]["Provider"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCredential"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Credential"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteCustomerCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
                provider: components["parameters"]["Provider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    setProjectCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
                provider: components["parameters"]["Provider"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCredential"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Credential"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteProjectCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
                provider: components["parameters"]["Provider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getProjectUsage: {
        parameters: {
            query?: {
                group_by?: "ticket" | "model";
                since?: string;
            };
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageReport"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listKnowledgeEntries: {
        parameters: {
            query?: {
                kind?: components["schemas"]["KnowledgeKind"];
                /** @description Project key */
                project?: string;
                /** @description Linked tracker item key */
                item?: string;
            };
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeEntryList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createKnowledgeEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateKnowledgeEntry"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeEntry"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    searchKnowledge: {
        parameters: {
            query: {
                q: string;
                kind?: components["schemas"]["KnowledgeKind"];
                project?: string;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSearchResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getKnowledgeEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
                /** @description Knowledge entry ID */
                entry: components["parameters"]["Entry"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeEntry"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateKnowledgeEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
                /** @description Knowledge entry ID */
                entry: components["parameters"]["Entry"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateKnowledgeEntry"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeEntry"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listKnowledgeVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer key */
                customer: components["parameters"]["Customer"];
                /** @description Knowledge entry ID */
                entry: components["parameters"]["Entry"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeVersionList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listSkills: {
        parameters: {
            query: {
                /** @description organization, customer:<key> or project:<key> */
                scope: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createSkill: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSkill"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Skill ID */
                skill: components["parameters"]["Skill"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateSkillDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Skill ID */
                skill: components["parameters"]["Skill"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSkillDraft"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    publishSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Skill ID */
                skill: components["parameters"]["Skill"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishSkill"];
            };
        };
        responses: {
            /** @description Published */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillVersion"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listSkillVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Skill ID */
                skill: components["parameters"]["Skill"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillVersionList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSkillVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Skill ID */
                skill: components["parameters"]["Skill"];
                number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillVersion"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    resolveProjectSkills: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedSkillList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProjectSkillPins: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSkillPinList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    pinProjectSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillPin"];
            };
        };
        responses: {
            /** @description Pinned */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    unpinProjectSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key */
                project: components["parameters"]["Project"];
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unpinned */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                kind?: "item" | "skill";
                /** @description Project key: its items and its skill chain */
                project?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
